/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as IqTestRouteImport } from './routes/iq-test'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OlympicsRouteImport } from './routes/olympics'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultRouteImport } from './routes/result'
import { Route as TrainRouteImport } from './routes/train'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const IqTestRoute = IqTestRouteImport.update({
  id: '/iq-test',
  path: '/iq-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OlympicsRoute = OlympicsRouteImport.update({
  id: '/olympics',
  path: '/olympics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/iq-test': typeof IqTestRoute
  '/leaderboard': typeof LeaderboardRoute
  '/olympics': typeof OlympicsRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/iq-test': typeof IqTestRoute
  '/leaderboard': typeof LeaderboardRoute
  '/olympics': typeof OlympicsRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/iq-test': typeof IqTestRoute
  '/leaderboard': typeof LeaderboardRoute
  '/olympics': typeof OlympicsRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/train': typeof TrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificate'
    | '/iq-test'
    | '/leaderboard'
    | '/olympics'
    | '/profile'
    | '/result'
    | '/train'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/iq-test'
    | '/leaderboard'
    | '/olympics'
    | '/profile'
    | '/result'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/certificate'
    | '/iq-test'
    | '/leaderboard'
    | '/olympics'
    | '/profile'
    | '/result'
    | '/train'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  IqTestRoute: typeof IqTestRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OlympicsRoute: typeof OlympicsRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  TrainRoute: typeof TrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq-test': {
      id: '/iq-test'
      path: '/iq-test'
      fullPath: '/iq-test'
      preLoaderRoute: typeof IqTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olympics': {
      id: '/olympics'
      path: '/olympics'
      fullPath: '/olympics'
      preLoaderRoute: typeof OlympicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  IqTestRoute: IqTestRoute,
  LeaderboardRoute: LeaderboardRoute,
  OlympicsRoute: OlympicsRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  TrainRoute: TrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
